1
CREATE VIEW SALES_PERSON AS
SELECT NAME,SALESMAN_ID,CITY FROM SALESMAN


2
CREATE VIEW DAILY_ORDERS AS
SELECT
COUNT(CUSTOMER_ID),
AVG(PURCHASE_AMT),
SUM(PURCHASE_AMT)
ORD_DATE
FROM ORDERS
GROUP BY ORDER_DATE


3
CREATE VIEW ORDERS_COUNT_DAILY AS
SELECT
COUNT(ORD_NO),
ORD_DATE
FROM ORDERS
GROUP BY ORD_DATE



CREATE VIEW ORDERS_COUNT_DAILY AS
COUNT(ORD_NO),
ORD_DATE
FROM ORDERS
GROUP BY ORD_DATE



CREATE MATERIALIZED VIEW COMPLEX_VIEW
AS
SELECT
AVG(P.PRICE),
COUNT(P.NAME),
SUM(P.PRICE)
M.NAME,
P.NAME
FROM PRODUCTS P LEFT JOIN MANUFACTURERS M ON(P.MANUFACTURER=M.CODE)
GROUP BY M.NAME,P.NAME


CREATE MATERIALIZED VIEW PRODUCT_SALE_MV
CREATE MATERIALIZED VIEW LOG ON PRODUCT_SALE_MV
REFRESH FAST
BUILD IMMEDIATE
AS
SELECT
SUM(S.QUQNTITY_SOLD),
SUM(S.AMOUNT_SOLD)
P.NAME
FROM PRODUCT P LEFT JOIN SALES ON(P.PROD_ID=S.PROD_ID)
GROUP BY P.NAME
